# Generated by Django 5.1.1 on 2024-10-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='banner',
        ),
        migrations.AddField(
            model_name='post',
            name='pdf_file',
            field=models.FileField(default='Example.pdf', upload_to='media'),
            preserve_default=False,
        ),
    ]
