# Generated by Django 5.1.1 on 2024-10-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_banner_post_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pdf_file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
