# Generated by Django 5.1.1 on 2024-10-24 03:34

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_pdf_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='abstract',
        ),
        migrations.AddField(
            model_name='post',
            name='license',
            field=models.CharField(choices=[('BY', 'CC BY'), ('SA', 'CC BY-SA'), ('NC', 'CC BY-NC'), ('BYNCSA', 'CC BY-NC-SA'), ('ND', 'CC BY-NC-ND')], default='CC BY', max_length=8),
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('Eng', 'Engineering'), ('Engl', 'English'), ('Arch', 'Architecture'), ('Bus', 'Business'), ('Com', 'Communications')], default='Computer Science', max_length=8),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
