# Generated by Django 5.1.1 on 2024-11-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_body_post_abstract_post_license_post_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='uploader',
        ),
    ]
