# Generated by Django 5.1.1 on 2024-11-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_author_post_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authors',
            field=models.CharField(default='Admin', max_length=255),
        ),
    ]
