# Generated by Django 5.1.3 on 2024-12-05 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_keywords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.TextField(help_text='Copy and Paste your abstract or introduction into this field'),
        ),
        migrations.AlterField(
            model_name='post',
            name='authors',
            field=models.CharField(default=' ', help_text='Please use full names separated by commas', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.CharField(default='Thesis', help_text='Please separate keywords by commas', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('Eng', 'Engineering'), ('Engl', 'English'), ('Arch', 'Architecture'), ('Bus', 'Business'), ('Com', 'Communications'), ('Math', 'Mathematics'), ('DS', 'Data Science')], default='Computer Science', max_length=8),
        ),
        migrations.AlterField(
            model_name='post',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
